name: Maven Release

on: workflow_dispatch

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-java-maven-release.yml@v2.1.8
    with:
      java-version: '21'
      mvn-parameters: install
    secrets: inherit